spring.application.name=hackathon-backend

# 1. Database Connection Info
spring.datasource.url=jdbc:postgresql://localhost:5432/hackathon
# 2. Database Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Credentials
spring.datasource.username=postgres
spring.datasource.password=admin

# 4. JPA / Hibernate Configurations for PostgreSQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
# spring.ai.google.genai.chat.model=gemini-3.1-flash-lite

llm.provider=gemini
llm.api-key=${GEMINI_API_KEY}
llm.model=gemini-3.1-flash-lite
llm.base-url=https://generativelanguage.googleapis.com

